### ISSUE TITLE
Query limit of 100

### ISSUE THREAD

**Issue by andrei-g-lupu** [JohnScooby/Google-Scraper#1]
Only gets top 100 search results. I use VS Code, is there a setting I need to tick?

**Comment by JohnScooby** [comment]
No Nothing Like That, It's Because Google Search Limits The Results By The num Parameter Till That Extent From Single Page.

To Overcome That You Can Add Another Parameter Called start To Get More Urls From It.

Like https://www.google.com/search?q=Hello&num=100&start=100 and https://www.google.com/search?q=Hello&num=100&start=200
